### ISSUE TITLE
[BUG]: APIv2 docker install broken

### ISSUE THREAD

**Issue by Repsay** [hashtopolis/server#1184]
### Version Information

docker install latest

### Hashcat

-

### Description

Connection to API v2 with new frontend is not working due to PHP fatal:

```
PHP Fatal error:  Uncaught Slim\Exception\HttpNotFoundException: Not found. in /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:76
Stack trace:
#0 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\Middleware\RoutingMiddleware->performRouting()
#1 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\RoutingMiddleware->process()
#2 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#3 /var/www/html/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle()
#4 /var/www/html/vendor/slim/slim/Slim/App.php(193): Slim\App->handle()
#5 /var/www/html/src/api/v2/index.php(284): Slim\App->run()
#6 {main}
  thrown in /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 76
```

**Comment by ObsidianOracle** [comment]
This should be fixed. If not, let us know so we can reopen the issue.

**Comment by tompako786-maker** [comment]
Issue is still there i got same error

PHP Fatal error:  Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:76\nStack trace:\n#0 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\\Middleware\\RoutingMiddleware->performRouting()\n#1 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\\Middleware\\RoutingMiddleware->process()\n#2 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#3 /var/www/html/vendor/slim/slim/Slim/App.php(209): Slim\\MiddlewareDispatcher->handle()\n#4 /var/www/html/vendor/slim/slim/Slim/App.php(193): Slim\\App->handle()\n#5 /var/www/html/src/api/v2/index.php(284): Slim\\App->run()\n#6 {main}\n  thrown in /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 76
