### ISSUE TITLE
[BUG]: Network error when opening Show Cracks

### ISSUE THREAD

**Issue by gpascal123** [hashtopolis/server#1415]
### Version Information

0.14.4

### Description

If we now call up the Show Cracks page, we get the known network error message after a few seconds.

http://localhost:8080/api/v2/ui/hashes?page%5Bsize%5D=100&page%5Bafter%5D=6477&include=hashlist,chunk&filter%5BisCracked__eq%5D=true

**Comment by ObsidianOracle** [comment]
Should be fixed once pagination is done.

**Comment by jessevz** [comment]
@gpascal123 pagination has been merged, can you still reproduce this issue or can this be closed?

**Comment by jessevz** [comment]
Seems to be fixed
