### ISSUE TITLE
[BUG]: Network error when opening the Dashboard

### ISSUE THREAD

**Issue by gpascal123** [hashtopolis/server#1416]
### Version Information

0.14.4

### Description

If we now call up the Dashboard page, we get the known network error message after a few seconds.

http://localhost:8080/api/v2/ui/hashes?filter%5BisCracked__eq%5D=1

**Comment by jessevz** [comment]
can you also add the response of the API call?

**Comment by gpascal123** [comment]
![Image](https://github.com/user-attachments/assets/d2fd4a79-331c-44d9-ae75-350bdcadb34f)

There is no response, you only get the 500.

**Comment by ObsidianOracle** [comment]
Should be fixed once pagination is done.

**Comment by jessevz** [comment]
@gpascal123 can you still reproduce this error? Or can I close this

**Comment by jessevz** [comment]
Seems to be fixed
